spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vollmed
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  error:
    include-stacktrace: never
api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}